---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-cloudflare-laininthewired-github-io-v1beta1-cloudflare
  failurePolicy: Fail
  name: mcloudflare-v1beta1.kb.io
  rules:
  - apiGroups:
    - cloudflare.laininthewired.github.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cloudflares
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cloudflare-laininthewired-github-io-v1beta1-cloudflare
  failurePolicy: Fail
  name: vcloudflare-v1beta1.kb.io
  rules:
  - apiGroups:
    - cloudflare.laininthewired.github.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cloudflares
  sideEffects: None
